import = ["~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"]
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1
blur = false

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 14
